/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pembukuan;


//import com.mysql.jdbc.Driver;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Claus
 */
public class inputKredit extends javax.swing.JFrame {
    DefaultTableModel model ;
    String barang,baranglama,id;//variabel penyimpanan sementara
    float beratBarang,beratLama;
    
    /**
     * Creates new form inputKredit
     */
    public inputKredit() {
        initComponents();
        combobox();
        String [] judul = {"No", "No.Nota", "Tanggal", "Nama Penjual", "Jenis Barang", "Bruto", "Tara Colly","PTGKadarAir", "PTGLain2","Netto", "Harga Satuan", "Harga Total", "Overhead","Lain-Lain","Jumlah"};
        model = new DefaultTableModel (judul,0);
        jTable1.setModel(model);
        tampilkan ();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        inputCari = new javax.swing.JTextField();
        buttonCari = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        judul = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        input2 = new com.toedter.calendar.JDateChooser();
        input3 = new javax.swing.JTextField();
        input1 = new javax.swing.JTextField();
        input4 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        input6 = new javax.swing.JTextField();
        input5 = new javax.swing.JTextField();
        input7 = new javax.swing.JTextField();
        input8 = new javax.swing.JTextField();
        input9 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tambahItemButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        input10 = new javax.swing.JTextField();
        input11 = new javax.swing.JTextField();
        input12 = new javax.swing.JTextField();
        input13 = new javax.swing.JTextField();
        buttonGanti = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonTambah = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        input14 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        actionButton = new javax.swing.JMenu();
        inputButton = new javax.swing.JMenuItem();
        stokButton = new javax.swing.JMenuItem();
        rekapButton = new javax.swing.JMenuItem();
        hutangButton = new javax.swing.JMenuItem();
        optionButton = new javax.swing.JMenuItem();
        quitButton = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 443));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "No_Nota", "Tanggal", "Nama_Penjual", "Jenis_Barang", "Bruto", "Tara_Colly", "PTGKadarAir", "PTGLain", "Netto", "Harga_Satuan", "Harga_Total", "Overhead", "Lain-Lain", "Jumlah"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        buttonCari.setText("Cari");
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });

        jLabel16.setText("Cari Berdasarkan Nama");

        judul.setFont(new java.awt.Font("Myriad Pro Light", 1, 18)); // NOI18N
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("Input Pengeluaran");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tanggal");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nama Penjual");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("No. Nota");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Jenis Barang");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Sisa Netto (Kg)");

        input6.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                input6InputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        input6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input6ActionPerformed(evt);
            }
        });
        input6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                input6KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input6KeyReleased(evt);
            }
        });

        input5.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                input5InputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        input5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input5ActionPerformed(evt);
            }
        });
        input5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                input5KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                input5KeyTyped(evt);
            }
        });

        input7.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                input7InputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        input7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input7ActionPerformed(evt);
            }
        });
        input7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                input7KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input7KeyReleased(evt);
            }
        });

        input8.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                input8InputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        input8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input8ActionPerformed(evt);
            }
        });
        input8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                input8KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input8KeyReleased(evt);
            }
        });

        input9.setEditable(false);
        input9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Bruto (Kg)");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tara Colly (Kg)");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Potongan :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Kadar Air (Kg)");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Lain-lain (Kg)");

        tambahItemButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tambahItemButton.setText("Tambah Jenis Barang");
        tambahItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahItemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jLabel9))
                                        .addComponent(jLabel10))
                                    .addGap(20, 20, 20)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(input8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(input9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(20, 20, 20)
                                    .addComponent(input6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(input7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(57, 57, 57)
                                    .addComponent(input5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(71, 71, 71)
                                    .addComponent(input1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(41, 41, 41)
                                    .addComponent(input4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tambahItemButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(input2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(input1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(input4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tambahItemButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(input5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(input6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(input7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(input8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(input9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Harga Satuan (Rp)");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Harga Total (Rp)");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Overhead (Rp)");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Lain-lain (Rp)");

        input10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input10KeyReleased(evt);
            }
        });

        input11.setEditable(false);
        input11.setBackground(new java.awt.Color(255, 255, 255));

        input12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input12KeyReleased(evt);
            }
        });

        input13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input13KeyReleased(evt);
            }
        });

        buttonGanti.setText("Ganti");
        buttonGanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGantiActionPerformed(evt);
            }
        });

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonTambah.setText("Tambah");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("JUMLAH (Rp)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(input10, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                    .addComponent(input11)
                                    .addComponent(input12)
                                    .addComponent(input13)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(buttonTambah)
                                .addGap(69, 69, 69)
                                .addComponent(buttonGanti)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addComponent(buttonHapus)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(input14)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(input10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(input11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(input12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(input14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTambah)
                    .addComponent(buttonGanti)
                    .addComponent(buttonHapus))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        jButton1.setText("Reset ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        actionButton.setText("Action");

        inputButton.setText("Input");
        inputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputButtonActionPerformed(evt);
            }
        });
        actionButton.add(inputButton);

        stokButton.setText("Stok");
        stokButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokButtonActionPerformed(evt);
            }
        });
        actionButton.add(stokButton);

        rekapButton.setText("Rekap");
        rekapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekapButtonActionPerformed(evt);
            }
        });
        actionButton.add(rekapButton);

        hutangButton.setText("Hutang/Piutang");
        hutangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hutangButtonActionPerformed(evt);
            }
        });
        actionButton.add(hutangButton);

        optionButton.setText("option");
        optionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionButtonActionPerformed(evt);
            }
        });
        actionButton.add(optionButton);

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        actionButton.add(quitButton);

        jMenuBar1.add(actionButton);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(4, 4, 4)
                                .addComponent(inputCari, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(buttonCari))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(275, 275, 275)
                                .addComponent(jButton1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel16))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(inputCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonCari))
                        .addGap(11, 11, 11)
                        .addComponent(jButton1)))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputButtonActionPerformed
        new debetKreditGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_inputButtonActionPerformed

    private void stokButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokButtonActionPerformed
        new stokBarangGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_stokButtonActionPerformed

    private void rekapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekapButtonActionPerformed
        new rekapGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rekapButtonActionPerformed

    private void hutangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hutangButtonActionPerformed
        new hutangGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hutangButtonActionPerformed

    private void optionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionButtonActionPerformed
        new optionGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_optionButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void input6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input6ActionPerformed
      
    }//GEN-LAST:event_input6ActionPerformed

    private void input5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input5ActionPerformed
        
    }//GEN-LAST:event_input5ActionPerformed

    private void input7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input7ActionPerformed
        
    }//GEN-LAST:event_input7ActionPerformed

    private void input8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input8ActionPerformed
       
    }//GEN-LAST:event_input8ActionPerformed

    private void input5InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_input5InputMethodTextChanged
    
    }//GEN-LAST:event_input5InputMethodTextChanged

    private void input6InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_input6InputMethodTextChanged
        
    }//GEN-LAST:event_input6InputMethodTextChanged

    private void input7InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_input7InputMethodTextChanged
      
    }//GEN-LAST:event_input7InputMethodTextChanged

    private void input8InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_input8InputMethodTextChanged
        
    }//GEN-LAST:event_input8InputMethodTextChanged

    private void input6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input6KeyPressed
        
    }//GEN-LAST:event_input6KeyPressed

    private void input5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input5KeyPressed
      
    }//GEN-LAST:event_input5KeyPressed

    private void input7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input7KeyPressed
        
    }//GEN-LAST:event_input7KeyPressed

    private void input8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input8KeyPressed
        
    }//GEN-LAST:event_input8KeyPressed

    private void input5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input5KeyTyped
        
    }//GEN-LAST:event_input5KeyTyped

    private void input5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input5KeyReleased
        kalkulasiNetto();
    }//GEN-LAST:event_input5KeyReleased

    private void input6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input6KeyReleased
        kalkulasiNetto();
    }//GEN-LAST:event_input6KeyReleased

    private void input7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input7KeyReleased
        kalkulasiNetto();
    }//GEN-LAST:event_input7KeyReleased

    private void input8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input8KeyReleased
        kalkulasiNetto();
    }//GEN-LAST:event_input8KeyReleased

    private void input10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input10KeyReleased
        kalkulasiNetto();
    }//GEN-LAST:event_input10KeyReleased

    private void input12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input12KeyReleased
        kalkulasiNetto();
    }//GEN-LAST:event_input12KeyReleased

    private void input13KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input13KeyReleased
        kalkulasiNetto();
    }//GEN-LAST:event_input13KeyReleased

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/pembukuan_toko99", "root", "");
            barang=input4.getSelectedItem().toString();
            SimpleDateFormat formatTgl = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal = formatTgl.format(input2.getDate());
            Statement stmt = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            
            cn.createStatement().executeUpdate("INSERT INTO pengeluaran (No_Nota,Tanggal,Nama_Penjual,Jenis_Barang,Bruto,Tara_Colly,Potongan_KadangAir,"
                    + "Potongan_Lain,Netto,Harga_Satuan,Harga_Total,Overhead,PengeluaranLain,Jumlah) VALUES"
                    +"('"+input1.getText()+"','"+tanggal+"','"+input3.getText()+"','"+barang+"','"+input5.getText()+"','"+input6.getText()
                    +"','"+input7.getText()+"','"+input8.getText()+"','"+input9.getText()+"','"+input10.getText()+"','"+input11.getText()
                    +"','"+input12.getText()+"','"+input13.getText()+"','"+input14.getText()+"')");
            
            ResultSet srs = stmt.executeQuery("SELECT stok FROM daftarbarang where barang='"+barang+"'");
            while (srs.next()) {                 
                 beratBarang = srs.getFloat("stok");                 
             }     
            beratBarang+=Float.parseFloat(input9.getText());
            
            cn.createStatement().executeUpdate("Update daftarbarang set stok='"+beratBarang+"' where barang='"+barang+"'");
            tampilkan();
        } catch (SQLException ex) {
            Logger.getLogger(inputKredit.class.getName()).log(Level.SEVERE, null, ex);
        }
        reset();
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void tambahItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahItemButtonActionPerformed
            new TambahJenisItemGUI().setVisible(true);
    }//GEN-LAST:event_tambahItemButtonActionPerformed

    private void buttonGantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGantiActionPerformed
       try {
            barang=input4.getSelectedItem().toString();
            SimpleDateFormat formatTgl = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal = formatTgl.format(input2.getDate());
                        
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/pembukuan_toko99", "root", "");
            Statement stmt = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
                           
            if(baranglama==barang){
               ResultSet srs = stmt.executeQuery("SELECT stok FROM daftarbarang where barang='"+barang+"'");
               while (srs.next()) {                 
                    beratBarang = srs.getFloat("stok");    //ambil data dari tabel daftar barang             
               }
               beratBarang=beratBarang-beratLama+Float.parseFloat(input9.getText());
            }                
            else{               
                ResultSet srs = stmt.executeQuery("SELECT stok FROM daftarbarang where barang='"+baranglama+"'");
                while (srs.next()) {                 
                    beratBarang = srs.getFloat("stok");    //ambil data dari tabel daftar barang        
                }
                beratBarang-=beratLama;
                cn.createStatement().executeUpdate("Update daftarbarang set stok='"+beratBarang+"' where barang= '"+baranglama+"'");
                
                srs = stmt.executeQuery("SELECT stok FROM daftarbarang where barang='"+barang+"'");
                while (srs.next()) {                 
                    beratBarang = srs.getFloat("stok");    //ambil data dari tabel daftar barang             
                }
                beratBarang+=Float.parseFloat(input9.getText());
            }  
            cn.createStatement().executeUpdate("Update daftarbarang set stok='"+beratBarang+"' where barang='"+barang+"'");
            
            cn.createStatement().executeUpdate("update pengeluaran set No_Nota='"+input1.getText()+"', Tanggal='"+tanggal
                    +"', Nama_Penjual='"+input3.getText()+"', Jenis_Barang='"+barang+"', Bruto='"+input5.getText()
                    +"', Tara_Colly='"+input6.getText()+"', Potongan_KadangAir= '"+input7.getText()+"', Potongan_Lain= '"+input8.getText()
                    +"', Netto='"+input9.getText()+"', Harga_Satuan = '"+input10.getText()+"', Harga_Total= '"+input11.getText()
                    +"', Overhead='"+input12.getText()+"', PengeluaranLain = '"+input13.getText()+"', Jumlah= '"+input14.getText()+"' where No_Pengeluaran='"+id+"'");        
            tampilkan();
        } catch (SQLException ex) {
            Logger.getLogger(inputKredit.class.getName()).log(Level.SEVERE, null, ex);
        }
       reset();
    }//GEN-LAST:event_buttonGantiActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        SimpleDateFormat formatTgl = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal;
        java.util.Date tanggals=new java.util.Date();       
        int i= jTable1.getSelectedRow();
        if (i>-1){
            id=model.getValueAt(i,0).toString();
            input1.setText(model.getValueAt(i,1).toString());//isi tabel ke textbox
            
            tanggal= model.getValueAt(i,2).toString();//isi tabel ke jcalendar
            try {
                tanggals= formatTgl.parse(tanggal);
            } catch (ParseException ex) {
                Logger.getLogger(inputKredit.class.getName()).log(Level.SEVERE, null, ex);
            }
            java.sql.Date tanggald=new java.sql.Date(tanggals.getTime());
            input2.setDate(tanggald);
            
            input3.setText(model.getValueAt(i,3).toString());
            input4.setSelectedItem(model.getValueAt(i,4));
            baranglama=model.getValueAt(i,4).toString();
            input5.setText(model.getValueAt(i,5).toString());
            input6.setText(model.getValueAt(i,6).toString());
            input7.setText(model.getValueAt(i,7).toString());
            input8.setText(model.getValueAt(i,8).toString());            
            beratLama=Float.parseFloat(model.getValueAt(i,9).toString());
            input9.setText(model.getValueAt(i,9).toString());
            input10.setText(model.getValueAt(i,10).toString());
            input11.setText(model.getValueAt(i,11).toString());
            input12.setText(model.getValueAt(i,12).toString());
            input13.setText(model.getValueAt(i,13).toString());
            input14.setText(model.getValueAt(i,14).toString());
            
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        try {
            
            barang=input4.getSelectedItem().toString();
            SimpleDateFormat formatTgl = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal = formatTgl.format(input2.getDate());
            
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/pembukuan_toko99", "root", "");
            Statement stmt = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet srs = stmt.executeQuery("SELECT stok FROM daftarbarang where barang='"+barang+"'");
            while (srs.next()) {                 
                 beratBarang = srs.getFloat("stok");                 
             }     
            beratBarang-=Float.parseFloat(input9.getText());
            
            cn.createStatement().executeUpdate("Update daftarbarang set stok='"+beratBarang+"' where barang='"+barang+"'");
            
            
            cn.createStatement().executeUpdate("delete from pengeluaran where No_Pengeluaran='"+id+"'");   
            tampilkan();
        } catch (SQLException ex) {
            Logger.getLogger(inputKredit.class.getName()).log(Level.SEVERE, null, ex);
        }
       reset();
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
        int row =jTable1.getRowCount ();
        for (int a=0; a<row;a++){
            model.removeRow (0);
        
        }
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/pembukuan_toko99", "root", "");
            ResultSet rs = cn.createStatement ().executeQuery(" select * from pengeluaran where Nama_Penjual Like '%"+inputCari.getText()+"%'");
            while (rs.next()){
               String data[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12),rs.getString(13),rs.getString(14),rs.getString(15)};
               model.addRow (data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(inputKredit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonCariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tampilkan();
        reset();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputKredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputKredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputKredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputKredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputKredit().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu actionButton;
    private javax.swing.JButton buttonCari;
    private javax.swing.JButton buttonGanti;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JMenuItem hutangButton;
    private javax.swing.JTextField input1;
    private javax.swing.JTextField input10;
    private javax.swing.JTextField input11;
    private javax.swing.JTextField input12;
    private javax.swing.JTextField input13;
    private javax.swing.JTextField input14;
    private com.toedter.calendar.JDateChooser input2;
    private javax.swing.JTextField input3;
    private javax.swing.JComboBox<String> input4;
    private javax.swing.JTextField input5;
    private javax.swing.JTextField input6;
    private javax.swing.JTextField input7;
    private javax.swing.JTextField input8;
    private javax.swing.JTextField input9;
    private javax.swing.JMenuItem inputButton;
    private javax.swing.JTextField inputCari;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel judul;
    private javax.swing.JMenuItem optionButton;
    private javax.swing.JMenuItem quitButton;
    private javax.swing.JMenuItem rekapButton;
    private javax.swing.JMenuItem stokButton;
    private javax.swing.JButton tambahItemButton;
    // End of variables declaration//GEN-END:variables

    private void kalkulasiNetto() {
        Float bruto,tara,air,beratLain,netto,hargaTotal;
        int hargaSatuan, hargaTotalInt,frak,lain,jumlah;
                
        if(input5.getText().isEmpty())
           bruto=0f;
        else bruto= Float.parseFloat(input5.getText());
        
        if(input6.getText().isEmpty())
            tara=0f;
        else tara= Float.parseFloat(input6.getText());
        
        if(input7.getText().isEmpty())
            air=0f;   
        else air= Float.parseFloat(input7.getText());
        
        if(input8.getText().isEmpty())
            beratLain=0f;
        else beratLain= Float.parseFloat(input8.getText());
        
        netto= bruto-(tara+air+beratLain);
        input9.setText(Float.toString(netto));
        
        if (input9.getText().isEmpty())
            netto=0f;
        else netto= Float.parseFloat(input9.getText());
        
        if (input10.getText().isEmpty())
            hargaSatuan=0;
        else hargaSatuan= Integer.parseInt(input10.getText());
        
        hargaTotal=netto*hargaSatuan;
        hargaTotalInt=Math.round(hargaTotal);
        input11.setText(Integer.toString(hargaTotalInt));
        
        if (input11.getText().isEmpty())
            hargaTotalInt=0;
        else hargaTotalInt=Integer.parseInt(input11.getText());
        
        if (input12.getText().isEmpty())
            frak=0;
        else frak=Integer.parseInt(input12.getText());
        
        if (input13.getText().isEmpty())
            lain=0;
        else lain=Integer.parseInt(input13.getText());
        
        jumlah=hargaTotalInt+frak+lain;
        input14.setText(Integer.toString(jumlah));
    }
    private void tampilkan() {
        int row =jTable1.getRowCount ();
        for (int a=0; a<row;a++){
            model.removeRow (0);        
        }
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/pembukuan_toko99", "root", "");
            ResultSet rs = cn.createStatement ().executeQuery(" select * from pengeluaran ");
            while (rs.next()){
               String data[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12),rs.getString(13),rs.getString(14),rs.getString(15)};
               model.addRow (data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(inputKredit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void combobox(){
        Connection con=null;
        PreparedStatement pst=null;
        ResultSet rs=null;
        try {            
          con= DriverManager.getConnection("jdbc:mysql://localhost/pembukuan_toko99", "root", "");
           String sql = "select * from daftarBarang";
           pst = con.prepareStatement(sql);
           rs = pst.executeQuery();
           while(rs.next())
           {
              String name = rs.getString("barang");
              input4.addItem(name);
           }
         } catch (Exception e){
        
        }
    }

    private void reset() {
       input1.setText("");
       input3.setText("");
       input5.setText("");
       input6.setText("");
       input7.setText("");
       input8.setText("");
       input9.setText("");
       input10.setText("");
       input11.setText("");
       input12.setText("");
       input13.setText("");
       input14.setText("");
    }
}
